# Generated by Django 3.1.3 on 2020-11-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('apprentice', models.BooleanField(default=False)),
                ('developer', models.BooleanField(default=False)),
                ('senior', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('master_snr_list', models.CharField(blank=True, max_length=700, null=True)),
                ('master_dev_list', models.CharField(blank=True, max_length=700, null=True)),
                ('master_app_list', models.CharField(blank=True, max_length=700, null=True)),
                ('last_sprint', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='randomise.team')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='randomise.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='main_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='randomise.team'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='randomise.team')),
            ],
            options={
                'unique_together': {('sprint', 'team')},
            },
        ),
    ]
