# Generated by Django 3.1.3 on 2020-11-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='main_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomise.team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomise.team'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='main_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomise.team'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomise.member'),
        ),
    ]
